In [2]:
#https://www.kaggle.com/uciml/zoo-animal-classification/home
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,accuracy_score,recall_score,confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
dataSet = pd.read_csv('zoo.csv')
dataSet.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

In [10]:
from sklearn.preprocessing import LabelEncoder
#final_data[:,4]=LabelEncoder().fit_transform(final_data[:,4])
dataSet['animal_name']=LabelEncoder().fit_transform(dataSet['animal_name'])

In [11]:
x=dataSet.drop('class_type',axis=1)
y=dataSet['class_type']

In [12]:
#train and test data set spilitting
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.40, random_state=101)

In [13]:
#creating and fitting random forest model
forest = RandomForestClassifier(n_estimators=500)
forest.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [14]:
print('Accuracy on the training subset: {:.3f}'.format(forest.score(X_train, y_train)))
print('Accuracy on the test subset: {:.3f}'.format(forest.score(X_test, y_test)))

Accuracy on the training subset: 1.000
Accuracy on the test subset: 0.951


In [15]:
#confusion matrix
predictions = forest.predict(X_test)
print(confusion_matrix(y_test,predictions))

[[13  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0]
 [ 0  1  0  1  0  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  4]]


In [17]:
#accuracy=(TP+TN)/(TP+TN+FP+FN)
print(accuracy_score(y_test,predictions))
#classification report
#print(classification_report(y_test,predictions))

0.951219512195
