In [1]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,accuracy_score,recall_score,confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
dataSet = pd.read_csv('sensor_readings_24.csv')
dataSet.head()

US1    US2    US3    US4  US5    US6  US7    US8    US9   US10  \
0  0.438  0.498  3.625  3.645  5.0  2.918  5.0  2.351  2.332  2.643   
1  0.438  0.498  3.625  3.648  5.0  2.918  5.0  2.637  2.332  2.649   
2  0.438  0.498  3.625  3.629  5.0  2.918  5.0  2.637  2.334  2.643   
3  0.437  0.501  3.625  3.626  5.0  2.918  5.0  2.353  2.334  2.642   
4  0.438  0.498  3.626  3.629  5.0  2.918  5.0  2.640  2.334  2.639   

         ...           US16   US17   US18   US19   US20   US21   US22   US23  \
0        ...          0.593  0.502  0.493  0.504  0.445  0.431  0.444  0.440   
1        ...          0.592  0.502  0.493  0.504  0.449  0.431  0.444  0.443   
2        ...          0.593  0.502  0.493  0.504  0.449  0.431  0.444  0.446   
3        ...          0.593  0.502  0.493  0.504  0.449  0.431  0.444  0.444   
4        ...          0.592  0.502  0.493  0.504  0.449  0.431  0.444  0.441   

    US24              Class  
0  0.429  Slight-Right-Turn  
1  0.429  Slight-Right-Turn  
2  0.429  Slight-Right-Turn  
3  0.429  Slight-Right-Turn  
4  0.429  Slight-Right-Turn  

[5 rows x 25 columns]

In [6]:
#catagorical feature for encoding purpose
from sklearn.preprocessing import LabelEncoder
dataSet['Class']=LabelEncoder().fit_transform(dataSet['Class'])

In [7]:
x=dataSet.drop('Class',axis=1)
y=dataSet['Class']

In [8]:
#train and test data set spilitting
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.40, random_state=101)

In [9]:
#creating and fitting random forest model
forest = RandomForestClassifier(n_estimators=500)
forest.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [10]:
print('Accuracy on the training subset: {:.3f}'.format(forest.score(X_train, y_train)))
print('Accuracy on the test subset: {:.3f}'.format(forest.score(X_test, y_test)))

Accuracy on the training subset: 1.000
Accuracy on the test subset: 0.994


In [11]:
#confusion matrix
predictions = forest.predict(X_test)
print(confusion_matrix(y_test,predictions))

[[878   3   2   4]
 [  0 842   0   0]
 [  2   2 127   0]
 [  0   1   0 322]]


In [13]:
#accuracy=(TP+TN)/(TP+TN+FP+FN)
print(accuracy_score(y_test,predictions))
#classification report
#print(classification_report(y_test,predictions))

0.993586807146
