In [1]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,accuracy_score,recall_score,confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataSet = pd.read_csv('red-wine-quality-cortez-et-al-2009.csv')
dataSet.head()
#dataSet.quality.unique()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
x = dataSet.drop("quality",axis=1)
y = dataSet["quality"]
#y=np.asarray(final_data["class"], dtype="|S6")
#x=np.asarray(final_data)

In [8]:
#train and test data set spilitting
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.30, random_state=42)

In [9]:
#creating and fitting random forest model
forest = RandomForestClassifier(n_estimators=500)
forest.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [10]:
print('Accuracy on the training subset: {:.3f}'.format(forest.score(X_train, y_train)))
print('Accuracy on the test subset: {:.3f}'.format(forest.score(X_test, y_test)))

Accuracy on the training subset: 1.000
Accuracy on the test subset: 0.667


In [11]:
#confusion matrix
predictions = forest.predict(X_test)
print(confusion_matrix(y_test,predictions))

[[  0   0   1   0   0   0]
 [  0   0  10   7   0   0]
 [  0   0 149  44   2   0]
 [  0   0  44 142  14   0]
 [  0   0   0  32  28   1]
 [  0   0   0   0   5   1]]


In [12]:
#accuracy=(TP+TN)/(TP+TN+FP+FN)
print(accuracy_score(y_test,predictions))
#matrix=confusion_matrix(y_test,predictions)
#simple=(matrix[0][0]+matrix[1][1])/(matrix[0][0]+matrix[0][1]+matrix[1][0]+matrix[1][1])
#print('simple accuracy: {:.3f}'.format(simple))
#classification report
#print(classification_report(y_test,predictions))

0.666666666667
