In [1]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,accuracy_score,recall_score,confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
dataSet = pd.read_csv('german_credit_data.csv',index_col=0)
dataSet.head()

Age     Sex  Job Housing Saving accounts Checking account  Credit amount  \
0   67    male    2     own             NaN           little           1169   
1   22  female    2     own          little         moderate           5951   
2   49    male    1     own          little              NaN           2096   
3   45    male    2    free          little           little           7882   
4   53    male    2    free          little           little           4870   

   Duration              Purpose  
0         6             radio/TV  
1        48             radio/TV  
2        12            education  
3        42  furniture/equipment  
4        24                  car

In [3]:
dataSet.fillna(method='bfill',inplace=True)
dataSet.head()

Age     Sex  Job Housing Saving accounts Checking account  Credit amount  \
0   67    male    2     own          little           little           1169   
1   22  female    2     own          little         moderate           5951   
2   49    male    1     own          little           little           2096   
3   45    male    2    free          little           little           7882   
4   53    male    2    free          little           little           4870   

   Duration              Purpose  
0         6             radio/TV  
1        48             radio/TV  
2        12            education  
3        42  furniture/equipment  
4        24                  car

In [4]:
#dataSet['Checking account'].unique()
from sklearn.preprocessing import LabelEncoder
target=dataSet['Checking account']
target=LabelEncoder().fit_transform(target)

dataSet.drop('Checking account',axis=1,inplace=True)

dataSet['Sex']=LabelEncoder().fit_transform(dataSet['Sex'])
dataSet['Housing']=LabelEncoder().fit_transform(dataSet['Housing'])
dataSet['Saving accounts']=LabelEncoder().fit_transform(dataSet['Saving accounts'])
dataSet['Purpose']=LabelEncoder().fit_transform(dataSet['Purpose'])


In [5]:
x=dataSet
y=target

In [9]:
#train and test data set spilitting
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.30, random_state=42)

In [10]:
#creating and fitting random forest model
forest = RandomForestClassifier(n_estimators=500)
forest.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [11]:
print('Accuracy on the training subset: {:.3f}'.format(forest.score(X_train, y_train)))
print('Accuracy on the test subset: {:.3f}'.format(forest.score(X_test, y_test)))

Accuracy on the training subset: 1.000
Accuracy on the test subset: 0.477


In [12]:
#confusion matrix
predictions = forest.predict(X_test)
print(confusion_matrix(y_test,predictions))

[[85 64  1]
 [58 57  1]
 [17 16  1]]


In [13]:
#accuracy=(TP+TN)/(TP+TN+FP+FN)
print(accuracy_score(y_test,predictions))
#classification report
#print(classification_report(y_test,predictions))

0.476666666667
