# Import Libraries

**Import the usual libraries for pandas and plotting. You can import sklearn later on.**

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,accuracy_score,recall_score,confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
dataSet = pd.read_csv('iris.csv')
dataSet.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
#catagorical feature for encoding purpose
final_data=dataSet.iloc[:,:].values
from sklearn.preprocessing import LabelEncoder
final_data[:,4]=LabelEncoder().fit_transform(final_data[:,4])
final_data=pd.DataFrame(final_data)
final_data.head()

0    1    2    3  4
0  5.1  3.5  1.4  0.2  0
1  4.9    3  1.4  0.2  0
2  4.7  3.2  1.3  0.2  0
3  4.6  3.1  1.5  0.2  0
4    5  3.6  1.4  0.2  0

In [4]:
a=final_data.rename( columns={4: "class"},inplace=True)
final_data.head()

0    1    2    3 class
0  5.1  3.5  1.4  0.2     0
1  4.9    3  1.4  0.2     0
2  4.7  3.2  1.3  0.2     0
3  4.6  3.1  1.5  0.2     0
4    5  3.6  1.4  0.2     0

In [5]:
x = final_data.drop("class",axis=1)
#y = final_data["class"]
y=np.asarray(final_data["class"], dtype="|S6")
x=np.asarray(final_data)

In [6]:
##to create a fixed larger dataframe that has new feature columns with dummy variables. Set this dataframe as final_data.
#cat_feats = ['species']
#final_data = pd.get_dummies(dataSet,columns=cat_feats,drop_first=True)
#final_data.head()


In [7]:
#train and test data set spilitting
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.30, random_state=101)

In [8]:
#creating and fitting random forest model
forest = RandomForestClassifier(n_estimators=500)
forest.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [9]:
print('Accuracy on the training subset: {:.3f}'.format(forest.score(X_train, y_train)))
print('Accuracy on the test subset: {:.3f}'.format(forest.score(X_test, y_test)))

Accuracy on the training subset: 1.000
Accuracy on the test subset: 1.000


In [10]:
#confusion matrix
predictions = forest.predict(X_test)
print(confusion_matrix(y_test,predictions))

[[13  0  0]
 [ 0 20  0]
 [ 0  0 12]]


In [11]:
#accuracy=(TP+TN)/(TP+TN+FP+FN)
#print(accuracy_score(y_test,predictions))
matrix=confusion_matrix(y_test,predictions)
simple=(matrix[0][0]+matrix[1][1])/(matrix[0][0]+matrix[0][1]+matrix[1][0]+matrix[1][1])
print('simple accuracy: {:.3f}'.format(simple))
#classification report
#print(classification_report(y_test,predictions))

simple accuracy: 1.000
